/**
 * Painted Lineage — contexts data model
 *
 * Single source of truth for the linear globe + walk.
 * Every pin in the painting's exhibition history is a Context object.
 * The globe renders all of them; the path threads them by date;
 * only `enterable` contexts stream a splat world.
 *
 * The Green Blouse (La Blouse verte / La Tasse de café)
 * Pierre Bonnard, 1919-20. The Metropolitan Museum of Art.
 */

export type Tier = "primary" | "transition" | "atlas";

export interface Context {
  /** Stable id, used for routing and world lookup. */
  id: string;
  /** Sort key. Real exhibition order is by this. ISO-ish; use the opening year. */
  year: number;
  /** Full date span for display, e.g. "Apr 24 – Jun 15, 1924" or "1939–1974". */
  dateLabel: string;
  /** Venue / institution as it should display. */
  venue: string;
  city: string;
  country: string;
  /** Real geographic position for the globe pin. [lat, lng]. */
  coords: [number, number];
  /** primary = built world + walk pause; transition = built world, walked through; atlas = pin only. */
  tier: Tier;
  /** Whether clicking the pin streams a world. true for primary + transition, false for atlas. */
  enterable: boolean;
  /** Splat world identifier (Marble world_id or local asset key). null until generated / for atlas pins. */
  worldId: string | null;
  /** Title the painting carried at this venue — the title-drift detail is load-bearing. */
  titleAtVenue: string;
  /** Catalogue number / note as published, for the metadata card. */
  catalogueNote: string;
  /** One-line curatorial note for the metadata card and dev reference. Optional. */
  note?: string;
  /** Marks the void. Exactly one context has this. Terminal node: cannot be Expanded. */
  isVoid?: boolean;
}

export const CONTEXTS: Context[] = [
  {
    id: "le-cannet-studio",
    year: 1919,
    dateLabel: "1919–20",
    venue: "Le Bosquet (the artist's studio)",
    city: "Le Cannet",
    country: "France",
    coords: [43.5806, 7.0103],
    tier: "primary",
    enterable: true,
    worldId: null,
    titleAtVenue: "—",
    catalogueNote: "No exhibition. The making. Sourced from Bonnard's villa, not a venue.",
    note: "The only primary not drawn from the exhibition record. Emotional ground floor.",
  },
  {
    id: "carnegie-1924",
    year: 1924,
    dateLabel: "Apr 24 – Jun 15, 1924",
    venue: "Carnegie Institute, 23rd Annual International",
    city: "Pittsburgh",
    country: "United States",
    coords: [40.4434, -79.9497],
    tier: "primary",
    enterable: true,
    worldId: null,
    titleAtVenue: "The Cup of Coffee",
    catalogueNote: "no. 126, lent by Bernheim Jeune et Cie.",
    note: "First public showing.",
  },
  {
    id: "wildenstein-1934",
    year: 1934,
    dateLabel: "Mar 1–24, 1934",
    venue: "Wildenstein & Co., Inc.",
    city: "New York",
    country: "United States",
    coords: [40.7714, -73.9676],
    tier: "transition",
    enterable: true,
    worldId: null,
    titleAtVenue: "The cup of coffee",
    catalogueNote: "no. 25 (as 1924).",
    note: "First Atlantic crossing. Passable room between Carnegie and Stockholm.",
  },
  {
    id: "stockholm-1939",
    year: 1939,
    dateLabel: "Mar 1939",
    venue: "Svensk-Franska Konstgalleriet",
    city: "Stockholm",
    country: "Sweden",
    coords: [59.3293, 18.0686],
    tier: "primary",
    enterable: true,
    worldId: null,
    titleAtVenue: "Le corsage vert",
    catalogueNote: "no. 23 (as 1920).",
    note: "Last show before the silence. The path arrives here and stops.",
  },
  {
    id: "the-silence",
    year: 1939,
    dateLabel: "1939–1974",
    venue: "The Bernheim de Villers collection (private)",
    city: "Paris",
    country: "France",
    coords: [48.8566, 2.3522],
    tier: "primary",
    enterable: true,
    worldId: null,
    titleAtVenue: "—",
    catalogueNote: "No entry. 35 years unexhibited. The gap itself.",
    note: "Withdrawal into private life, NOT war looting. 5-cube 1.1 Plus void. Terminal: cannot be Expanded.",
    isVoid: true,
  },
  {
    id: "met-impressionist-epoch-1974",
    year: 1974,
    dateLabel: "Dec 12, 1974 – Feb 10, 1975",
    venue: 'The Metropolitan Museum of Art, "The Impressionist Epoch"',
    city: "New York",
    country: "United States",
    coords: [40.7794, -73.9632],
    tier: "primary",
    enterable: true,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "Not in catalogue.",
    note: "The resurrection. Re-entry without a catalogue entry — model as a missing wall placard.",
  },
  {
    id: "whatcom-1976",
    year: 1976,
    dateLabel: "Dec 4, 1976 – Oct 2, 1977",
    venue: 'Whatcom Museum, "5000 Years of Art" (Met collection)',
    city: "Bellingham",
    country: "United States",
    coords: [48.7519, -122.4787],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "no. 75.",
  },
  {
    id: "nyu-grey-1978",
    year: 1978,
    dateLabel: "May 2 – Jun 2, 1978",
    venue: 'Grey Art Gallery, NYU, "Changes in Perspective: 1880–1925"',
    city: "New York",
    country: "United States",
    coords: [40.7295, -73.9965],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "unnumbered (p. 10).",
  },
  {
    id: "bordeaux-1981",
    year: 1981,
    dateLabel: "May 15 – Sep 1, 1981",
    venue: 'Galerie des Beaux-Arts, "Profil du Metropolitan Museum"',
    city: "Bordeaux",
    country: "France",
    coords: [44.8412, -0.5800],
    tier: "transition",
    enterable: true,
    worldId: null,
    titleAtVenue: "Le Corsage vert",
    catalogueNote: "no. 219.",
    note: "First return to France since 1962. French title resurfaces — placard must be legible.",
  },
  {
    id: "san-diego-1981",
    year: 1981,
    dateLabel: "Oct 10 – Dec 6, 1981",
    venue: 'San Diego Museum of Art, "5,000 Years of Art" (Met collection)',
    city: "San Diego",
    country: "United States",
    coords: [32.7300, -117.1490],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "brochure no. 70.",
  },
  {
    id: "krannert-1982",
    year: 1982,
    dateLabel: "Jan 3 – Feb 28, 1982",
    venue: 'Krannert Art Museum, "5,000 Years of Art" (Met collection)',
    city: "Urbana-Champaign",
    country: "United States",
    coords: [40.1020, -88.2272],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "brochure no. 70.",
  },
  {
    id: "mobile-1982",
    year: 1982,
    dateLabel: "Mar 28 – May 9, 1982",
    venue: 'Fine Arts Museum of the South, "5,000 Years of Art" (Met collection)',
    city: "Mobile",
    country: "United States",
    coords: [30.6954, -88.0399],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "brochure no. 70.",
  },
  {
    id: "midland-1982",
    year: 1982,
    dateLabel: "Jun 6 – Aug 22, 1982",
    venue: 'Midland Center for the Arts, "5,000 Years of Art" (Met collection)',
    city: "Midland",
    country: "United States",
    coords: [43.6156, -84.2472],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "brochure no. 70.",
  },
  {
    id: "little-rock-1982",
    year: 1982,
    dateLabel: "Sep 19 – Nov 14, 1982",
    venue: 'Arkansas Arts Center, "5,000 Years of Art" (Met collection)',
    city: "Little Rock",
    country: "United States",
    coords: [34.7465, -92.2896],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "brochure no. 70.",
  },
  {
    id: "zurich-1984",
    year: 1984,
    dateLabel: "Dec 14, 1984 – Mar 10, 1985",
    venue: 'Kunsthaus Zürich, "Bonnard"',
    city: "Zürich",
    country: "Switzerland",
    coords: [47.3700, 8.5483],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "La Blouse verte / La Tasse de café",
    catalogueNote: "no. 92.",
  },
  {
    id: "frankfurt-1985",
    year: 1985,
    dateLabel: "May 3 – Jul 14, 1985",
    venue: 'Städelsches Kunstinstitut, "Bonnard"',
    city: "Frankfurt",
    country: "Germany",
    coords: [50.1040, 8.6745],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "La Blouse verte / La Tasse de café",
    catalogueNote: "no. 92.",
  },
  {
    id: "met-selection-two-1985",
    year: 1985,
    dateLabel: "Jun 4 – Sep 2, 1985",
    venue: 'The Metropolitan Museum of Art, "Selection Two: Twentieth-Century Art"',
    city: "New York",
    country: "United States",
    coords: [40.7794, -73.9632],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "no catalogue.",
  },
  {
    id: "canberra-1986",
    year: 1986,
    dateLabel: "Mar 1 – Apr 27, 1986",
    venue: 'Australian National Gallery, "20th Century Masters" (Met)',
    city: "Canberra",
    country: "Australia",
    coords: [-35.3000, 149.1374],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "unnumbered (p. 29).",
  },
  {
    id: "brisbane-1986",
    year: 1986,
    dateLabel: "May 7 – Jul 1, 1986",
    venue: 'Queensland Art Gallery, "20th Century Masters" (Met)',
    city: "Brisbane",
    country: "Australia",
    coords: [-27.4705, 153.0235],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "unnumbered.",
  },
  {
    id: "yokohama-1989",
    year: 1989,
    dateLabel: "Mar 25 – Jun 4, 1989",
    venue: 'Yokohama Museum of Art, "Treasures from The Met"',
    city: "Yokohama",
    country: "Japan",
    coords: [35.4571, 139.6320],
    tier: "primary",
    enterable: true,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "no. 152.",
    note: "The Pacific crossing. Chosen over the 1997 Tokyo monographic shows for the diaspora-by-sea note.",
  },
  {
    id: "louisiana-1992",
    year: 1992,
    dateLabel: "Sep 11, 1992 – Jan 10, 1993",
    venue: 'Louisiana Museum, "Pierre Bonnard"',
    city: "Humlebæk",
    country: "Denmark",
    coords: [55.9697, 12.5430],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "La Blouse verte / La Tasse de café",
    catalogueNote: "no. 52.",
  },
  {
    id: "dusseldorf-1993",
    year: 1993,
    dateLabel: "Jan 23 – Apr 12, 1993",
    venue: 'Kunstsammlung Nordrhein-Westfalen, "Das Glück zu malen"',
    city: "Düsseldorf",
    country: "Germany",
    coords: [51.2255, 6.7763],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "La Blouse verte",
    catalogueNote: "no. 23.",
  },
  {
    id: "munich-1994",
    year: 1994,
    dateLabel: "Jan 28 – Apr 24, 1994",
    venue: 'Kunsthalle der Hypo-Kulturstiftung, "Bonnard"',
    city: "Munich",
    country: "Germany",
    coords: [48.1393, 11.5762],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "Die grüne Bluse / Die Tasse Kaffee",
    catalogueNote: "no. 80.",
  },
  {
    id: "nagoya-1997",
    year: 1997,
    dateLabel: "Mar 28 – May 18, 1997",
    venue: 'Aichi Prefectural Museum of Art, "Pierre Bonnard"',
    city: "Nagoya",
    country: "Japan",
    coords: [35.1709, 136.9085],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "no. 59.",
  },
  {
    id: "tokyo-bunkamura-1997",
    year: 1997,
    dateLabel: "May 24 – Jul 21, 1997",
    venue: 'Bunkamura Museum of Art, "Pierre Bonnard"',
    city: "Tokyo",
    country: "Japan",
    coords: [35.6586, 139.6979],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "no. 59.",
  },
  {
    id: "met-painters-in-paris-2000",
    year: 2000,
    dateLabel: "Mar 8, 2000 – Jan 14, 2001",
    venue: 'The Metropolitan Museum of Art, "Painters in Paris: 1895–1950"',
    city: "New York",
    country: "United States",
    coords: [40.7794, -73.9632],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "unnumbered (p. 40).",
  },
  {
    id: "kyoto-2002",
    year: 2002,
    dateLabel: "Sep 14 – Nov 24, 2002",
    venue: 'Kyoto Municipal Museum of Art, "Picasso and the School of Paris" (Met)',
    city: "Kyoto",
    country: "Japan",
    coords: [35.0116, 135.7831],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "no. 36.",
  },
  {
    id: "tokyo-bunkamura-2002",
    year: 2002,
    dateLabel: "Dec 7, 2002 – Mar 9, 2003",
    venue: 'Bunkamura Museum of Art, "Picasso and the School of Paris" (Met)',
    city: "Tokyo",
    country: "Japan",
    coords: [35.6586, 139.6979],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "no. 36.",
  },
  {
    id: "paris-mam-2006",
    year: 2006,
    dateLabel: "Feb 2 – May 7, 2006",
    venue: 'Musée d\'Art Moderne de la Ville de Paris, "L\'Œuvre d\'art, un arrêt du temps"',
    city: "Paris",
    country: "France",
    coords: [48.8642, 2.2967],
    tier: "primary",
    enterable: true,
    worldId: null,
    titleAtVenue: "La Blouse verte (La Tasse de café)",
    catalogueNote: "no. 52.",
    note: "The full homecoming. Source of the project epigraph.",
  },
  {
    id: "houston-2007",
    year: 2007,
    dateLabel: "Feb 4 – May 6, 2007",
    venue: 'Museum of Fine Arts, Houston, "Masterpieces of French Painting" (Met)',
    city: "Houston",
    country: "United States",
    coords: [29.7257, -95.3905],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "no. 123.",
  },
  {
    id: "berlin-2007",
    year: 2007,
    dateLabel: "Jun 1 – Oct 7, 2007",
    venue: 'Neue Nationalgalerie, "Französische Meisterwerke" (Met)',
    city: "Berlin",
    country: "Germany",
    coords: [52.5061, 13.3676],
    tier: "atlas",
    enterable: false,
    worldId: null,
    titleAtVenue: "The Green Blouse",
    catalogueNote: "unnumbered (p. 245).",
  },
  {
    id: "stockholm-nationalmuseum-2025",
    year: 2025,
    dateLabel: "Feb 19 – May 18, 2025",
    venue: 'Nationalmuseum, "Bonnard och Norden"',
    city: "Stockholm",
    country: "Sweden",
    coords: [59.3286, 18.0780],
    tier: "primary",
    enterable: true,
    worldId: null,
    titleAtVenue: "Den gröna blusen (La Blouse verte)",
    catalogueNote: "no. 35.",
    note: "Nordic loop opens. Path returns to Stockholm — 86 years after it went dark there.",
  },
  {
    id: "lillehammer-2025",
    year: 2025,
    dateLabel: "Jun 14 – Oct 19, 2025",
    venue: 'Lillehammer Kunstmuseum, "Bonnard og Norden"',
    city: "Lillehammer",
    country: "Norway",
    coords: [61.1153, 10.4662],
    tier: "primary",
    enterable: true,
    worldId: null,
    titleAtVenue: "Den grønne blusen",
    catalogueNote: "no. 35.",
    note: "The present. Final pin. A short northern hop closes a life of ocean crossings.",
  },
];

/** The date-ordered path. Already sorted, but sort explicitly so the source order can't drift. */
export const PATH = [...CONTEXTS].sort((a, b) => a.year - b.year);

/** The enterable subset — what streams a world. Primary + transition. */
export const ENTERABLE = CONTEXTS.filter((c) => c.enterable);

/** NYC pins share a coordinate cluster and need fan-out on the globe. */
export const COLOCATION_CLUSTERS: Record<string, string[]> = {
  "new-york": [
    "wildenstein-1934",
    "met-impressionist-epoch-1974",
    "nyu-grey-1978",
    "met-selection-two-1985",
    "met-painters-in-paris-2000",
  ],
};
