/**
 * The real painting, composited into each world.
 *
 * Marble renders an approximate, hallucinated canvas on the wall where the
 * prompt asks for "a framed Bonnard painting." For fidelity we cover that with
 * the actual Met open-access scan (`/the-green-blouse.jpg`): a flat textured
 * plane in the Three scene, positioned to sit a hair in front of the splat's
 * canvas, inside Marble's gilt frame. The frame stays Marble's; the canvas
 * becomes the real one.
 *
 * Marble decides where the wall lands, so each world's placement is hand-tuned
 * AFTER its splat exists — walk it in the preview, nudge position/rotation/size,
 * screenshot to confirm the canvas sits flush in the frame. Mirrors the
 * per-world calibration of WORLD_AUDIO.
 *
 * A world with no entry here renders no plane (the studio is intentionally
 * absent — its painting is on the easel, unfinished, generated by Marble).
 */

import * as THREE from "three";

/** Default canvas: the Met open-access scan, 428×625 (aspect ≈ 0.685). */
export const PAINTING_URL = "/the-green-blouse.jpg";
export const PAINTING_ASPECT = 428 / 625;

export interface PaintingPlacement {
  /** World-space center of the canvas (camera spawns near [0,1.6,0]). */
  position: [number, number, number];
  /** Euler rotation (radians) — align the plane flat against the wall. */
  rotation: [number, number, number];
  /** Canvas height in meters; width is derived from the scan's aspect. */
  height: number;
  /** Override the canvas image (defaults to The Green Blouse scan). */
  url?: string;
  /** Override the aspect (w/h) if using a non-default image. */
  aspect?: number;
}

/**
 * Per-world painting placements. Empty until each splat exists and is
 * calibrated. Template (copy, uncomment, dial in once the splat streams):
 *
 *   "carnegie-1924": { position: [0, 1.5, -4], rotation: [0, 0, 0], height: 0.9 },
 *
 * The void carries it too — dim and unlabeled — but as a domestic object, not a
 * hung exhibit (see docs/WORLD_GEN.md §5).
 */
export const WORLD_PAINTING: Record<string, PaintingPlacement> = {
  // Calibrated against the Gemini→Marble splat: the empty gold frame on the
  // central pier sits at z≈-17.75; the plane rides ~0.55m in front so the
  // splat's white-canvas gaussians don't occlude it. Opening ≈1.6m tall.
  "carnegie-1924": {
    position: [0, 1.47, -17.2],
    rotation: [0, 0, 0], // faces +Z, down the hall toward the spawn
    height: 1.82, // fills the gold opening with an even thin gold reveal around
  },
  // Wildenstein's gold portrait frame: triangulated (two straight-on −Z views)
  // to a ~1.0×1.55m opening (aspect 0.649) centered at world (−0.052, ~1.11,
  // −11.9) — the townhouse hall is huge, the frame ~12m down. The opening's
  // 0.649 aspect is NARROWER than the painting's 0.685, so even gilt reveal on
  // all four sides is impossible without distorting the scan (never do that).
  // Instead height fills the opening so the canvas slightly over-covers the
  // gilt lip uniformly (no black-liner gap); centered on both axes. Plane 0.5m
  // front. Re-calibrated 2026-06-05 via the crisp-magenta method (swap the plane
  // to a solid color for hard edges, nest it in the opening): the old
  // [−0.045,1.088] h1.47 sat right+down (black liner showed L/T) and over-tall
  // (rode past the gilt onto the walnut top/bottom). Now centered on the opening
  // and sized so the canvas rides the gilt lip with an even reveal per pair
  // (L/R ~10/13px, T/B ~28px in the calibration shot), no liner gap on any edge.
  "wildenstein-1934": {
    position: [-0.052, 1.11, -11.4],
    rotation: [0, 0, 0], // faces +Z toward the spawn
    height: 1.34,
  },
  // Stockholm's tall gold portrait frame on the axial end wall. Depth
  // triangulated from two straight-on −Z views (opening ≈277px tall at z=−3,
  // ≈477px at z=−6 → frame plane z≈−10.16; the room is deep). Opening ≈1.31×2.02m
  // (aspect ≈0.649, NARROWER than the 0.685 scan) so — per the Wildenstein rule —
  // height (2.05) over-covers the opening: the canvas rides the gilt lip on all
  // sides with no white gaps, centered on both axes. Verified seated at z=−3.5
  // (spawn) and z=−6.5 (close); parallax nulled. Frame center slightly +x/+y.
  "stockholm-1939": {
    position: [0.15, 1.8, -10.16],
    rotation: [0, 0, 0], // faces +Z toward the spawn
    height: 2.05,
  },
  // The void's frontal portrait frame, deep down a long apartment enfilade.
  // Triangulated from two straight-on −Z views (opening ≈220px at z=0, ≈345px at
  // z=−2.5 → frame plane z≈−6.9; the room is deep) and parallax-nulled at both
  // distances. Opening aspect ≈0.64 (narrower than the 0.685 scan) so — per the
  // Wildenstein/Stockholm rule — height (1.58) over-covers: the canvas rides the
  // gilt lip with an even reveal, no liner gap. NOT lit, NOT labeled (no placard
  // entry) — "hung as if lived with, not shown." The void grade desaturates +
  // dims the plane along with the room, so the scan needs no separate dark asset.
  "the-silence": {
    position: [-0.55, 1.38, -6.9],
    rotation: [0, 0, 0], // faces +Z toward the spawn
    height: 1.66,
  },
  // Met-74: the resurrection. Frontal gilt frame on the central pier; depth
  // triangulated from two straight-on −Z views (opening ≈109px @ cam z=0, ≈254px
  // @ z=−4.5 → frame plane z≈−7.9), parallax-nulled. WHY THIS WORLD NEEDS A CROP:
  // Marble WIDENED + WARPED the frame's opening to ≈0.75 (cream canvas), much wider
  // than the 0.685 scan AND off-center (~0.03m LEFT of the pier axis) — because the
  // gold frame sits on a gold/ochre wall (low contrast: Marble couldn't trace the
  // gilt edges, so it reconstructed a generic, off-center opening; Stockholm/void
  // kept their aspect because their frames were against PALE walls). Seating the full
  // 0.685 scan meant white side-gaps or heavy over-cover; seating it at x=0 overhung
  // the RIGHT gilt onto the wall. FIX (per-world): a cropped scan
  // `/the-green-blouse-met74.jpg` = the Met scan with 54px off the TOP only
  // (sky/curtain — the expendable region; figures, table, AND bottom-left signature
  // all preserved) → aspect 0.749 matching the opening, recentered to x=−0.03 → fills
  // snugly with an even thin gilt reveal, no distortion, no side overhang. Plane
  // floated 0.5m proud (z=−7.4) so the opaque material isn't washed out (verified:
  // 0.25m float washes out to bare cream canvas, 0.4m+ crisp, 0.5m safe). Full color,
  // NO grade, NO placard (the bare wall beside the frame is the missing label).
  "met-impressionist-epoch-1974": {
    position: [-0.03, 1.32, -7.4],
    rotation: [0, 0, 0], // faces +Z toward the spawn
    height: 1.489,
    url: "/the-green-blouse-met74.jpg",
    aspect: 0.749,
  },
  // Bordeaux v2 (flat-frame re-splat). v1 reconstructed the dark frame as a deep
  // shadowbox → the flat painting plane floated/parallax-separated at oblique angles
  // (unfixable: depth-bias just traded forward-float for always-on-top; carving rejected).
  // Re-splatted from a still prompted for a SLIM, FLAT, FLUSH frame. v2's frame is flat/
  // shallow, so the painting seats FLUSH (no proud float) and stays crisp head-on with NO
  // wash-out — the float v1/met-74 needed is gone. Depth triangulated with the magenta
  // probe (frame plane ≈ z−24.3; the v2 nave is deeper, parallax-nulled at z−10/−17).
  // Opening ≈0.69 portrait (aspect held again via dark-on-pale contrast), centered at
  // (−0.13, 1.30). DEPTH RE-FIT (2026-06-06): the head-on parallax-null under-read the
  // frame depth by ~1m — first put the plane at z−24.3, which floated/separated at steep
  // close OBLIQUE walk-ups (painting sat ~1m proud of the real frame). Re-fit with an
  // OBLIQUE camera (lateral parallax is far more depth-sensitive than head-on): true frame
  // plane ≈ z−25.4. LESSON: verify frame depth from an OBLIQUE view, not just head-on.
  // Seated flush there, crisp (no wash-out), registered in the frame at oblique — only the
  // natural thin frame-border edge shows at an angle (correct), no detached float. height
  // 1.130 = uniform over-cover sized to the deeper (larger) opening, no distortion. No
  // float, no aspect/url override. (v1 backup: [-0.06,1.02,-22.1] h1.03 @ bordeaux-1981.spz.)
  "bordeaux-1981": {
    position: [-0.16, 1.30, -25.4], // x nudged −0.13→−0.16 to center in the frame (left/bottom-left border was showing)
    rotation: [0, 0, 0], // faces +Z toward the spawn
    height: 1.130,
  },
  // Canberra: dark near-black FLAT frame on the pale board-formed concrete pier (a
  // freestanding center wall, symmetric arched passages either side — the Carnegie/
  // Met-74 center-pier composition, but symmetric so it holds as a head-on hero).
  // The dark-on-pale contrast let Marble preserve the source aspect: the splat opening
  // measures ≈0.68, essentially the 0.685 scan — so NO crop/aspect override needed
  // (unlike met-74), the scan fills with an even thin dark reveal. Depth: head-on
  // triangulation (200px@z2.916 / 317px@z0.6) first gave z≈−3.36, but per the Bordeaux
  // rule that UNDER-READ — the OBLIQUE view showed the plane separated ~0.4m laterally
  // off the real opening. Re-fit from oblique registration: true frame plane z≈−3.77
  // (rescaled height for the deeper/larger opening). Verified registered at far + close
  // + steep oblique. Frame is FLAT (only a slim molding shows at oblique, not a shadowbox)
  // so the painting seats FLUSH at the frame plane with NO proud float and NO wash-out
  // (emulated the real opaque depthTest material at z−3.77: crisp, no gaussian bleed —
  // same flush behavior as bordeaux v2). No placard (Canberra isn't a label world).
  "canberra-1986": {
    position: [0.02, 1.31, -3.77], // nudged +x/+y from (0,1.29) to close a faint bare-canvas
    rotation: [0, 0, 0], // sliver at the top + upper-right (opening is a hair larger/up-right there)
    height: 1.48, // was 1.43; bumped to over-cover onto the dark molding lip (invisible — frame is dark)
  },
  // Yokohama-1989: slim FLAT dark frame on the pale end wall of the deep skylit
  // Minato Mirai hall (Marble gave the prompted flat end-wall composition, not a
  // pier — a tall blank bay flanked by symmetric side galleries). The dark-on-pale
  // contrast preserved the source aspect: splat opening ≈0.71, close enough to the
  // 0.685 scan that — like Canberra — NO crop/aspect override is needed; the scan
  // fills with an even dark reveal. DEPTH — the lesson bit, and the most extreme yet:
  // head-on two-view triangulation (140px@z0 / 258px@z−6) AND the head-on parallax-
  // null both read the frame plane at ≈z−11, but the OBLIQUE view showed the painting
  // floating LEFT of the frame — head-on UNDER-READ the depth by ~2m (vs Bordeaux's
  // ~1m, Canberra's ~0.4m). Re-fit from oblique registration (swept z until the canvas
  // registered with the splat frame from BOTH left and right oblique, min lateral
  // separation): true frame plane z≈−13. Frame is FLAT so the canvas seats FLUSH with
  // NO proud float and NO wash-out (verified razor-crisp at 4m close head-on, signature
  // legible — the real opaque depthTest material, same flush behavior as bordeaux v2 /
  // canberra). height over-covers onto the dark frame lip (invisible) to close faint
  // bare-canvas slivers; height 1.564 + y lowered to 1.176 biases the over-cover
  // downward to also close a sliver under the bottom edge. Centered −0.018 on the frame
  // x. No placard (Yokohama isn't a label world).
  "yokohama-1989": {
    position: [-0.018, 1.176, -13],
    rotation: [0, 0, 0], // faces +Z toward the spawn
    height: 1.564,
  },
  // Paris-mam-2006 (the homecoming): slim dark frame on the pale central pier of the
  // warm enfilade gallery. Dark-on-pale preserved the source aspect (splat opening ≈0.66–0.68,
  // close to the 0.685 scan) so — like Canberra/Yokohama — NO crop/url override; the scan
  // fills with an even dark reveal. DEPTH was the fight: this frame did NOT reconstruct flat —
  // Marble gave it real DEPTH (a shallow shadowbox; the 2D gate-3 "slightly proud bevel" watch
  // was real). Head-on the painting seated cleanly at z≈−5.2, but per the Bordeaux/Yokohama rule
  // the OBLIQUE view exposed it: at z−5.2/−5.3 the canvas floated DETACHED, proud of the dark
  // opening (the frame visible as a separate rectangle behind it). With ZERO re-splat buffer we
  // can't re-splat to a flat frame (the Bordeaux-v1 fix) — so seated at the splat's CANVAS plane
  // z≈−5.4, the deepest point that stays visible (anything ≤−5.5 is occluded by the pale canvas
  // gaussians). There the painting REGISTERS in the dark opening from BOTH left and right oblique
  // (only a thin soft frame-edge shows — the natural recessed-painting read, no detached float)
  // AND stays crisp head-on (figures/fruit/signature all legible — it's at, not behind, the
  // surface). height 1.08 over-covers onto the dark lip (invisible) to close a bare-canvas sliver
  // under the bottom edge; y lowered to 1.32 biases the over-cover downward. Centered x=0. Full
  // color, NO grade, NO placard (Paris isn't a label world — only Wildenstein/Bordeaux/Met-74 are).
  "paris-mam-2006": {
    position: [0, 1.32, -5.4],
    rotation: [0, 0, 0], // faces +Z toward the spawn
    height: 1.08,
  },
};

/**
 * Composite a world's real painting into an existing Three scene.
 * Returns a cleanup function. Safe to call with an unknown id (no-op).
 */
export function initWorldPainting(
  scene: THREE.Scene,
  worldId: string | undefined,
  ready?: Promise<unknown>,
): () => void {
  const placement = worldId ? WORLD_PAINTING[worldId] : undefined;
  if (!placement) return () => {};

  const url = placement.url ?? PAINTING_URL;
  const aspect = placement.aspect ?? PAINTING_ASPECT;
  const width = placement.height * aspect;

  const geometry = new THREE.PlaneGeometry(width, placement.height);
  const material = new THREE.MeshBasicMaterial({
    side: THREE.DoubleSide,
    toneMapped: false, // a splat scene is unlit — show the scan at true value
    transparent: false,
  });
  const mesh = new THREE.Mesh(geometry, material);
  mesh.position.set(...placement.position);
  mesh.rotation.set(...placement.rotation);
  scene.add(mesh);

  let disposed = false;

  // The 100KB scan loads instantly; the splat streams + GPU-uploads + depth-sorts
  // over seconds. Hold the painting hidden until `ready` so it appears IN the
  // gallery, not floating in blur before the room exists.
  if (ready) {
    mesh.visible = false;
    ready.then(() => {
      // `ready` is WorldViewer's displayReady — it resolves only once the splat
      // has actually PAINTED (its sorted geometry went non-empty), not merely
      // decoded. Wait two extra frames as a safety margin so the reveal can never
      // land a frame ahead of the room.
      requestAnimationFrame(() =>
        requestAnimationFrame(() => {
          if (!disposed) mesh.visible = true;
        }),
      );
    });
  }
  const loader = new THREE.TextureLoader();
  loader.load(
    url,
    (texture) => {
      if (disposed) {
        texture.dispose();
        return;
      }
      texture.colorSpace = THREE.SRGBColorSpace;
      material.map = texture;
      material.needsUpdate = true;
    },
    undefined,
    () => {
      // Scan missing — leave the bare plane rather than throw.
    },
  );

  return () => {
    disposed = true;
    scene.remove(mesh);
    geometry.dispose();
    material.map?.dispose();
    material.dispose();
  };
}
