/**
 * The real painting, composited into each world.
 *
 * Marble renders an approximate, hallucinated canvas on the wall where the
 * prompt asks for "a framed Bonnard painting." For fidelity we cover that with
 * the actual Met open-access scan (`/the-green-blouse.jpg`): a flat textured
 * plane in the Three scene, positioned to sit a hair in front of the splat's
 * canvas, inside Marble's gilt frame. The frame stays Marble's; the canvas
 * becomes the real one.
 *
 * Marble decides where the wall lands, so each world's placement is hand-tuned
 * AFTER its splat exists — walk it in the preview, nudge position/rotation/size,
 * screenshot to confirm the canvas sits flush in the frame. Mirrors the
 * per-world calibration of WORLD_AUDIO.
 *
 * A world with no entry here renders no plane (the studio is intentionally
 * absent — its painting is on the easel, unfinished, generated by Marble).
 */

import * as THREE from "three";

/** Default canvas: the Met open-access scan, 428×625 (aspect ≈ 0.685). */
export const PAINTING_URL = "/the-green-blouse.jpg";
export const PAINTING_ASPECT = 428 / 625;

export interface PaintingPlacement {
  /** World-space center of the canvas (camera spawns near [0,1.6,0]). */
  position: [number, number, number];
  /** Euler rotation (radians) — align the plane flat against the wall. */
  rotation: [number, number, number];
  /** Canvas height in meters; width is derived from the scan's aspect. */
  height: number;
  /** Override the canvas image (defaults to The Green Blouse scan). */
  url?: string;
  /** Override the aspect (w/h) if using a non-default image. */
  aspect?: number;
}

/**
 * Per-world painting placements. Empty until each splat exists and is
 * calibrated. Template (copy, uncomment, dial in once the splat streams):
 *
 *   "carnegie-1924": { position: [0, 1.5, -4], rotation: [0, 0, 0], height: 0.9 },
 *
 * The void carries it too — dim and unlabeled — but as a domestic object, not a
 * hung exhibit (see docs/WORLD_GEN.md §5).
 */
export const WORLD_PAINTING: Record<string, PaintingPlacement> = {
  // Calibrated against the Gemini→Marble splat: the empty gold frame on the
  // central pier sits at z≈-17.75; the plane rides ~0.55m in front so the
  // splat's white-canvas gaussians don't occlude it. Opening ≈1.6m tall.
  "carnegie-1924": {
    position: [0, 1.47, -17.2],
    rotation: [0, 0, 0], // faces +Z, down the hall toward the spawn
    height: 1.82, // fills the gold opening with an even thin gold reveal around
  },
  // Wildenstein's gold portrait frame: triangulated (two straight-on −Z views)
  // to a ~1.0×1.55m opening (aspect 0.649) centered at world (−0.045, ~1.09,
  // −11.9) — the townhouse hall is huge, the frame ~12m down. The opening's
  // 0.649 aspect is NARROWER than the painting's 0.685, so even gilt reveal on
  // all four sides is impossible without distorting the scan (never do that).
  // Instead height fills the opening so the canvas slightly over-covers the
  // gilt lip uniformly (no white gaps); centered on both axes. Plane 0.5m front.
  "wildenstein-1934": {
    position: [-0.045, 1.088, -11.4],
    rotation: [0, 0, 0], // faces +Z toward the spawn
    height: 1.47,
  },
};

/**
 * Composite a world's real painting into an existing Three scene.
 * Returns a cleanup function. Safe to call with an unknown id (no-op).
 */
export function initWorldPainting(
  scene: THREE.Scene,
  worldId: string | undefined,
  ready?: Promise<unknown>,
): () => void {
  const placement = worldId ? WORLD_PAINTING[worldId] : undefined;
  if (!placement) return () => {};

  const url = placement.url ?? PAINTING_URL;
  const aspect = placement.aspect ?? PAINTING_ASPECT;
  const width = placement.height * aspect;

  const geometry = new THREE.PlaneGeometry(width, placement.height);
  const material = new THREE.MeshBasicMaterial({
    side: THREE.DoubleSide,
    toneMapped: false, // a splat scene is unlit — show the scan at true value
    transparent: false,
  });
  const mesh = new THREE.Mesh(geometry, material);
  mesh.position.set(...placement.position);
  mesh.rotation.set(...placement.rotation);
  scene.add(mesh);

  let disposed = false;

  // The 100KB scan loads instantly; the 28MB splat streams over seconds. Hold
  // the painting hidden until the splat is ready so it appears IN the gallery,
  // not floating in blur before the room exists.
  if (ready) {
    mesh.visible = false;
    ready.then(() => {
      if (!disposed) mesh.visible = true;
    });
  }
  const loader = new THREE.TextureLoader();
  loader.load(
    url,
    (texture) => {
      if (disposed) {
        texture.dispose();
        return;
      }
      texture.colorSpace = THREE.SRGBColorSpace;
      material.map = texture;
      material.needsUpdate = true;
    },
    undefined,
    () => {
      // Scan missing — leave the bare plane rather than throw.
    },
  );

  return () => {
    disposed = true;
    scene.remove(mesh);
    geometry.dispose();
    material.map?.dispose();
    material.dispose();
  };
}
